# Generated by Django 2.2.28 on 2023-11-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='Team_Member',
        ),
    ]
